<!-- BEGIN Navigation -->
<div class="navbar-wrapper">
  <div class="container">
    <nav class="navbar navbar-inverse navbar-static-top">
      <div class="container">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
          <span class="sr-only">Toggle Navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="/index.shtml">Anarchy</a>
      </div>
      <div id="navbar" class="navbar-collapse collapse" aria-expanded="false">
        <ul class="nav navbar-nav">
          <li>
            <a href="/index.shtml">Home</a>
          </li>
          <li>
            <a href="/about.shtml">About</a>
          </li>
          <li>
            <a href="/contact.shtml">Contact</a>
          </li>
        </ul>
    </div>
  </div>
    </nav>
  </div>
</div>

<!-- END Navigation -->
